import { BlogPost } from './types';

export const blogPosts: BlogPost[] = [
  {
    id: '1',
    title: 'Top 10 Hidden Gems in Southeast Asia You Must Visit in 2025',
    slug: 'hidden-gems-southeast-asia-2025',
    excerpt: 'Beyond the crowded temples of Angkor Wat and the party beaches of Koh Samui lie extraordinary destinations that most travelers never discover.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1552465011-b4e21bf6e79a?w=800&q=80',
    author: 'Sarah Chen',
    category: 'Destinations',
    publishedAt: '2025-03-15',
    readTime: '8 min read',
  },
  {
    id: '2',
    title: 'The Ultimate Guide to Traveling Solo Safely',
    slug: 'ultimate-guide-solo-travel-safety',
    excerpt: 'Solo travel is one of the most transformative experiences you can have. Here is everything you need to know to do it confidently and safely.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800&q=80',
    author: 'Marco Rivera',
    category: 'Tips & Advice',
    publishedAt: '2025-02-28',
    readTime: '12 min read',
  },
  {
    id: '3',
    title: 'How to Pack a 7-Day International Trip in One Carry-On',
    slug: 'pack-7-day-trip-one-carry-on',
    excerpt: 'Master the art of minimalist packing and save hundreds on checked baggage fees while traveling lighter and smarter.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1553913861-c0fddf2619ee?w=800&q=80',
    author: 'Aisha Patel',
    category: 'Tips & Advice',
    publishedAt: '2025-02-10',
    readTime: '6 min read',
  },
  {
    id: '4',
    title: 'Why Japan Should Be Your Next Travel Destination',
    slug: 'why-japan-next-destination',
    excerpt: 'From the neon chaos of Tokyo to the serene bamboo forests of Arashiyama, Japan is a country of extraordinary contrasts that rewards every traveler.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=800&q=80',
    author: 'David Kim',
    category: 'Destinations',
    publishedAt: '2025-01-22',
    readTime: '10 min read',
  },
  {
    id: '5',
    title: 'Sustainable Travel: How to Explore the World Responsibly',
    slug: 'sustainable-travel-guide',
    excerpt: 'Climate-conscious travel is not just a trend — it is an imperative. Discover how to reduce your carbon footprint while still having incredible adventures.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800&q=80',
    author: 'Emma Thompson',
    category: 'Sustainability',
    publishedAt: '2025-01-05',
    readTime: '9 min read',
  },
  {
    id: '6',
    title: 'The Best Time to Visit the Maldives: Month by Month Guide',
    slug: 'best-time-visit-maldives',
    excerpt: 'Perfect weather, optimal marine life encounters, and best prices — we break down every month to help you plan your dream Maldives escape.',
    content: 'Lorem ipsum dolor sit amet...',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80',
    author: 'James Wilson',
    category: 'Planning',
    publishedAt: '2024-12-18',
    readTime: '7 min read',
  },
];
